import HeroBg from '../components/home/section_Hero'
import Footer from '../components/footer'
import { db } from '../lib/firebase'
import React from 'react'
import Head from 'next/head'
import SectionBeneficios from '../components/home/section_Beneficios'
import Header2 from '../components/header/header'
import productProps from '../@types/productHome'
import Section_EmAlta from '../components/home/section_emAlta'
import Section_Categoria from '../components/home/section_Categorias'
import Section_ModaFeminina from '../components/home/section_ModaFeminina'

interface Props {
  products: productProps[]
}

export const getStaticProps = async () => {

  const productsDocs = await db.collection('products').get()

  const products = productsDocs.docs.map(e =>
    JSON.parse(JSON.stringify(e.data()))

  )

  return {
    props: {
      products: products
    }
  }
}

const Home: React.FC<Props> = ({ products }) => {

  // const [lazy_section_bestSellers, setLazy_section_bestSellers] = useState(false)
  // const [lazy_section_category, setLazy_section_category] = useState(false)
  // const [lazy_section_mda_feminin, setLazy_section_mda_feminin] = useState(false)

  // const SectionCategorias_Ref = useRef(null)
  // const SectionBestSellers_Ref = useRef(null)
  // const SectionMdaFeminin_Ref = useRef(null)
  // const options = {
  //   root: null,
  //   rootMargin: '1px',
  //   threshold: 0.1
  // }

  // const isSectionCategoryVisibile = useElementOnScreen(options, SectionCategorias_Ref)
  // const isSectionBestSellersVisibile = useElementOnScreen(options, SectionBestSellers_Ref)
  // const isSectionMdaFemininVisibile = useElementOnScreen(options, SectionBestSellers_Ref)

  // useEffect(() => {
  //   if (isSectionCategoryVisibile) {
  //     setLazy_section_category(true)
  //   }
  //   if (isSectionBestSellersVisibile) {
  //     setLazy_section_bestSellers(true)
  //   }
  // }, [
  //   isSectionCategoryVisibile,
  //   isSectionBestSellersVisibile,
  //   isSectionMdaFemininVisibile
  // ])

  // const [openCategory, setOpenCategory] = useState('400px')


  return (
    <>
      <Head>
        <title>Noir Shopping</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta content="index, follow" name="robots" />
        <meta name="theme-color" content="#3b82f6" />
        <meta
          data-rh="true"
          name="keywords"
          content=""
        />
      </Head>
      <Header2 />
      <main className="w-screen bg-zinc-100">
        <HeroBg />
        <SectionBeneficios />
        <Section_EmAlta products={products} />
        <Section_Categoria />
        <Section_ModaFeminina />
      </main>
      <Footer />
    </>
  )
}

export default Home
